BEGIN TRANSACTION;
DROP TABLE IF EXISTS info;
DROP TABLE IF EXISTS diagrams;
DROP TABLE IF EXISTS state;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS diagram_info;
DROP TABLE IF EXISTS tree_nodes;
COMMIT;
