/* Autogenerated with DRAKON Editor 1.31 */
#include "NexoFast.h"

#include <stdbool.h>
#include "Interface.h"

struct CurrentTransactionData g_Ctd;
struct NexoConfiguration g_Nexo;
static enum ProcedureResult Card_Validity_Check(void);

static enum ProcedureResult Check_Online_Performed(void);

static enum ProcedureResult Check_Service_Start_Conditions(void);

static enum ProcedureResult Cvc_Check_Amount(void);

static enum ProcedureResult Dcc_Processing(void);

static enum ProcedureResult Default_Service_Initialisation(void);

static enum ProcedureResult Financial_Application_Startup(void);

static void Initialise_Basic_Data(void);

static void Initialise_Transaction_Database(void);

static enum ProcedureResult Kernel_Activation(void);

static enum ProcedureResult Kernel_Processing(void);

static enum ProcedureResult Online_Request(void);

static enum ProcedureResult Outcome_Processing(void);

static enum ProcedureResult Perform_Service(void);

static enum ProcedureResult Pre_Processing(void);

static void Process_Accept(void);

static enum ProcedureResult Process_Acquirer_Preselection(void);

static void Process_AdditionalTrxData(void);

static enum ProcedureResult Process_Amount_Entry(void);

static enum ProcedureResult Process_Card_Inserted(void);

static enum ProcedureResult Process_Card_Swiped(void);

static enum ProcedureResult Process_Choice_of_Application(void);

static enum ProcedureResult Process_Event(void);

static enum ProcedureResult Process_Language_Selection(void);

static enum ProcedureResult Process_Manual_Entry(void);

static enum ProcedureResult Process_Profile_Parameters(void);

static enum ProcedureResult Process_Reference_Entry(void);

static enum ProcedureResult Process_Service_Selection(void);

static enum ProcedureResult Profile_Selection(void);

static enum ProcedureResult Service_Initialisation(void);

static enum ProcedureResult Technology_Selection(void);

static enum ProcedureResult Transaction_Completion(void);

static enum ProcedureResult Transaction_Dcc_Eligibility(void);

static enum ProcedureResult Upa_Specific_Processing(void);

static enum ProcedureResult Update_Pre_Authorisation(void);







static enum ProcedureResult Card_Validity_Check(void) {
    int _sw6950000_ = 0;
    // item 1729
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 651 */
    result =
    Pre_Processing();
    
    // item 652
    if (PR_OK == result) {
    } else {
        goto item_718;
    }
    
    item_655 :
    result = 
    Technology_Selection();
    
    // item 6680001
    if (result == PR_NON_EMV) {
        /* item 721 */
        goto item_718;
    } else {
    }
    
    // item 6680002
    if (result == PR_NOK) {
        goto item_718;
    } else {
    }
    
    item_656 :
    result =
    Profile_Selection();
    
    // item 6570001
    if (result == PR_OK) {
        /* item 676 */
        result =
        Cvc_Check_Amount();
    } else {
        goto item_6570002;
    }
    
    // item 677
    if (PR_OK == result) {
        goto item_898;
    } else {
        goto item_718;
    }
    
    item_6570002 :
    if (result == PR_TAP_AGAIN) {
        goto item_655;
    } else {
    }
    
    // item 6570003
    if (result == PR_END_APPLICATION) {
    } else {
        goto item_719;
    }
    
    item_689 :
    result =
    Outcome_Processing();
    
    // item 693
    if (PR_OK == result) {
    } else {
        goto item_718;
    }
    
    // item 690
    if (g_Ctd.Outcome == O_ONLINE_REQUEST) {
        goto item_719;
    } else {
        /* item 692 */
        result =
        Online_Request();
    }
    
    // item 726
    if (PR_OK == result) {
        /* item 6950000 */
        _sw6950000_ = g_Ctd.Out.Start;
    } else {
        goto item_718;
    }
    
    // item 6950001
    if (_sw6950000_ == NONE) {
        /* item 702 */
        result =
        Check_Online_Performed();
    } else {
        goto item_6950002;
    }
    
    // item 703
    if (PR_OK == result) {
        goto item_719;
    } else {
        goto item_718;
    }
    
    item_6950002 :
    if (_sw6950000_ == B) {
        goto item_655;
    } else {
    }
    
    // item 6950003
    if (_sw6950000_ == C) {
        goto item_656;
    } else {
    }
    
    // item 6950004
    if (_sw6950000_ == D) {
    } else {
        goto item_718;
    }
    
    item_898 :
    Dcc_Processing();
    /* item 681 */
    result =
    Kernel_Activation();
    
    // item 682
    if (PR_OK == result) {
        /* item 686 */
        result =
        Kernel_Processing();
    } else {
        goto item_718;
    }
    
    // item 687
    if (PR_OK == result) {
        goto item_689;
    } else {
    }
    
    item_718 :
    g_Ctd.TransactionResult = T_ABORTED;
    
    item_719 :
    Transaction_Completion();
    /* item 1730 */
    return result;
    
}

static enum ProcedureResult Check_Online_Performed(void) {
    // item 1763
    return PR_OK;
    
}

static enum ProcedureResult Check_Service_Start_Conditions(void) {
    // item 1774
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 1717 */
    result = PR_CONDITIONS_SATISFIED;
    /* item 1773 */
    return result;
    
}

static enum ProcedureResult Cvc_Check_Amount(void) {
    // item 758
    if (g_Nexo.CvcDefaultAmount) {
        /* item 761 */
        g_Ctd.TransactionAmount = *g_Nexo.CvcDefaultAmount;
    } else {
    }
    
    // item 1747
    return PR_OK;
    
}

static enum ProcedureResult Dcc_Processing(void) {
    // item 858
    g_Ctd.DccPerformedOnce = true;
    /* item 859 */
    Transaction_Dcc_Eligibility();
    
    // item 860
    if (g_Ctd.isDccEligible) {
        /* item 863 */
        HAP_Online_Request_to_Dcc_Provider();
    } else {
        goto item_1750;
    }
    
    // item 864
    if (g_Ctd.isDccEligible) {
        /* item 865 */
        SCAP_Cardholder_Confirmation();
    } else {
    }
    
    item_1750 :
    return PR_DONE;
    
}

static enum ProcedureResult Default_Service_Initialisation(void) {
    // item 1777
    enum ProcedureResult result = PR_UNINITIALISED;
    
    // item 1510
    if (g_Ctd.SelectedService
    ==
    S_CARDHOLDER_DETECTION) {
        /* item 1529 */
        g_Ctd.SelectedService = S_NONE;
        /* item 1530 */
        DeactivateAllInterfaces();
        /* item 1531 */
        result =
        Output(0x1E);
    } else {
        goto item_1542;
    }
    
    // item 1532
    if (PR_DONE == result) {
    } else {
        goto item_1538;
    }
    
    item_1542 :
    if ((g_Nexo.DefaultService == S_NONE) || (g_Nexo.DefaultService == S_CARDHOLDER_DETECTION)) {
        goto item_1538;
    } else {
        /* item 1513 */
        g_Ctd.SelectedService = g_Nexo.DefaultService;
        /* item 1514 */
        g_Ctd.SelectedLanguage = g_Nexo.CardholderDefaultLanguage;
        /* item 1515 */
        Initialise_Basic_Data();
        /* item 1545 */
        result =
        Service_Initialisation();
    }
    
    // item 1546
    if (PR_OK == result) {
        goto item_1778;
    } else {
    }
    
    item_1538 :
    result = PR_NOK;
    
    item_1778 :
    return result;
    
}

static enum ProcedureResult Financial_Application_Startup(void) {
    // item 1509
    /* item 1866 */
    return PR_OK;
    
}

static void Initialise_Basic_Data(void) {
}

static void Initialise_Transaction_Database(void) {
}

static enum ProcedureResult Kernel_Activation(void) {
    // item 1753
    return PR_OK;
    
}

static enum ProcedureResult Kernel_Processing(void) {
    // item 1756
    return PR_OK;
    
}

static enum ProcedureResult Online_Request(void) {
    // item 1762
    return PR_OK;
    
}

static enum ProcedureResult Outcome_Processing(void) {
    // item 1759
    return PR_OK;
    
}

static enum ProcedureResult Perform_Service(void) {
    int _sw16980000_ = 0;
    // item 1837
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 16980000 */
    _sw16980000_ = g_Ctd.SelectedService;
    
    // item 16980001
    if (_sw16980000_ == S_UPDATE_PRE_AUTH) {
        /* item 1713 */
        result =
        Update_Pre_Authorisation();
        goto item_1906;
    } else {
    }
    
    // item 16980002
    if (_sw16980000_ == S_CARD_VALIDITY_CHECK) {
        /* item 1712 */
        result =
        Card_Validity_Check();
    } else {
        /* item 1706 */
        g_Ctd.NokReason = N_NOT_IMPLEMENTED;
        /* item 1910 */
        g_Ctd.TerminalErrorReason = TER_NOT_IMPLEMENTED;
        goto item_1912;
    }
    
    item_1906 :
    if (PR_DONE == result) {
    } else {
        /* item 1915 */
        g_Ctd.NokReason = N_TECHNICAL_ERROR;
        /* item 1916 */
        g_Ctd.TerminalErrorReason = TE_NEXO_FAST_FAILURE;
        goto item_1912;
    }
    
    // item 1715
    if (g_Ctd.TerminalErrorIndicator) {
        /* item 1711 */
        result = PR_NOK;
        goto item_1823;
    } else {
        /* item 1716 */
        result = PR_OK;
        goto item_1823;
    }
    
    item_1912 :
    g_Ctd.TransactionResult = T_ABORTED;
    /* item 1913 */
    g_Ctd.TerminalErrorIndicator = true;
    /* item 1905 */
    result = PR_INTERNAL_ERROR;
    
    item_1823 :
    return result;
    
}

static enum ProcedureResult Pre_Processing(void) {
    // item 1736
    enum ProcedureResult result = PR_UNINITIALISED;
    
    // item 837
    if ((g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .referenceEntry) && (!(S_NO_SHOW == g_Ctd.SelectedService))) {
        /* item 841 */
        result = PR_REFERENCE_ENTRY;
    } else {
        /* item 1738 */
        result = PR_NOT_IMPLEMENTED;
    }
    
    // item 1735
    return result;
    
}

static void Process_Accept(void) {
}

static enum ProcedureResult Process_Acquirer_Preselection(void) {
    // item 1799
    return PR_NOT_IMPLEMENTED;
    
}

static void Process_AdditionalTrxData(void) {
}

static enum ProcedureResult Process_Amount_Entry(void) {
    // item 1803
    return PR_NOT_IMPLEMENTED;
    
}

static enum ProcedureResult Process_Card_Inserted(void) {
    // item 1806
    return PR_NOT_IMPLEMENTED;
    
}

static enum ProcedureResult Process_Card_Swiped(void) {
    // item 1809
    return PR_NOT_IMPLEMENTED;
    
}

static enum ProcedureResult Process_Choice_of_Application(void) {
    // item 1790
    return PR_NOT_IMPLEMENTED;
    
}

static enum ProcedureResult Process_Event(void) {
    // item 1841
    enum ProcedureResult result = PR_UNINITIALISED;
    
    // item 1375
    if (g_Ctd.Event[E_LANGUAGE_SELECTION]) {
        /* item 1378 */
        result =
        Process_Language_Selection();
    } else {
        goto item_1380;
    }
    
    // item 1379
    if (PR_OK == result) {
    } else {
        goto item_1464;
    }
    
    item_1380 :
    if (g_Ctd.Event[E_CHOICE_OF_APPLICATION]) {
        /* item 1383 */
        result =
        Process_Choice_of_Application();
    } else {
        goto item_1387;
    }
    
    // item 1384
    if (PR_OK == result) {
    } else {
        goto item_1464;
    }
    
    item_1387 :
    if (g_Ctd.Event[E_SERVICE_SELECTION]) {
        /* item 1390 */
        result =
        Process_Service_Selection();
    } else {
        goto item_1392;
    }
    
    // item 1391
    if (PR_OK == result) {
    } else {
        goto item_1464;
    }
    
    item_1392 :
    if (g_Ctd.Event[E_ACQUIRER_PRESELECTION]) {
        /* item 1395 */
        Process_Acquirer_Preselection();
    } else {
        goto item_1465;
    }
    
    // item 1396
    if (PR_OK == result) {
    } else {
        goto item_1464;
    }
    
    item_1465 :
    if (g_Ctd.Event[E_CARDHOLDER_DETECTION]) {
        /* item 1468 */
    } else {
        goto item_1401;
    }
    
    // item 1469
    if (PR_OK == result) {
    } else {
        goto item_1464;
    }
    
    item_1401 :
    if (g_Ctd.Event[E_AMOUNT_ENTRY]) {
        /* item 1403 */
        result =
        Process_Amount_Entry();
    } else {
        goto item_1425;
    }
    
    // item 1404
    if (PR_DONE == result) {
    } else {
        /* item 1406 */
        result =
        OutputAmountError();
        goto item_1407;
    }
    
    // item 1408
    if (g_Ctd.TransactionAmount.i == 0) {
        goto item_1425;
    } else {
        /* item 1410 */
        result =
        OutputTransactionAmount();
    }
    
    // item 1411
    if (PR_DONE == result) {
        goto item_1425;
    } else {
        goto item_1464;
    }
    
    item_1407 :
    if (PR_DONE == result) {
        goto item_1463;
    } else {
        goto item_1464;
    }
    
    item_1425 :
    if (g_Ctd.Event[E_CARD_INSERTED]) {
        /* item 1428 */
        result =
        Process_Card_Inserted();
    } else {
        goto item_1432;
    }
    
    // item 1429
    if (PR_DONE == result) {
    } else {
        goto item_1463;
    }
    
    item_1432 :
    if (g_Ctd.Event[E_CARD_SWIPED]) {
        /* item 1435 */
        result =
        Process_Card_Swiped();
    } else {
        goto item_1437;
    }
    
    // item 1436
    if (PR_DONE == result) {
    } else {
        goto item_1463;
    }
    
    item_1437 :
    if (g_Ctd.Event[E_MANUAL_ENTRY]) {
        /* item 1440 */
        result =
        Process_Manual_Entry();
    } else {
        goto item_1442;
    }
    
    // item 1441
    if (PR_DONE == result) {
    } else {
        goto item_1463;
    }
    
    item_1442 :
    if (g_Ctd.Event[E_REFERENCE_ENTRY]) {
        /* item 1445 */
        result =
        Process_Reference_Entry();
    } else {
        goto item_1446;
    }
    
    // item 1686
    if (PR_REINITIALISE == result) {
        goto item_1463;
    } else {
    }
    
    // item 1687
    if (PR_DONE == result) {
        goto item_1446;
    } else {
    }
    
    item_1464 :
    result = PR_REINITIALISE;
    goto item_1691;
    
    item_1446 :
    if (g_Ctd.Event[E_ACCEPT]) {
        /* item 1449 */
        Process_Accept();
    } else {
    }
    
    // item 1450
    if (g_Ctd.Event[E_ATTENDANT_FORCED_ONLINE]) {
        /* item 1453 */
        g_Ctd.
        AttendantForcedTransactionOnline = true;
    } else {
    }
    
    // item 1454
    if (g_Ctd.Event[E_ADDITIONAL_TRANSACTION_DATA]) {
        /* item 1457 */
        Process_AdditionalTrxData();
    } else {
    }
    
    // item 1458
    if (g_Ctd.Event[E_CARD_REMOVAL]) {
        /* item 1460 */
        g_Nexo.ServiceStartEvents
        [g_Ctd.SelectedService]
        .cardInserted = 0;
        goto item_1463;
    } else {
    }
    
    // item 1461
    if (g_Ctd.Event[E_CANCEL]) {
    } else {
        /* item 1695 */
        result = PR_OK;
        goto item_1691;
    }
    
    item_1463 :
    result = PR_REINITIALISE;
    
    item_1691 :
    /* item 1719 */
    return result;
    
}

static enum ProcedureResult Process_Language_Selection(void) {
    // item 1787
    return PR_NOT_IMPLEMENTED;
    
}

static enum ProcedureResult Process_Manual_Entry(void) {
    // item 1812
    return PR_NOT_IMPLEMENTED;
    
}

static enum ProcedureResult Process_Profile_Parameters(void) {
    // item 1831
    return PR_OK;
    
}

static enum ProcedureResult Process_Reference_Entry(void) {
    int _sw16500000_ = 0;
    // item 1815
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 16500000 */
    _sw16500000_ = g_Ctd.SelectedService;
    
    // item 16500001
    if (((((((_sw16500000_ == S_DEFFERED_PAYMENT_COMPLETION) || (_sw16500000_ == S_CANCELLATION)) || (_sw16500000_ == S_UPDATE_PRE_AUTH)) || (_sw16500000_ == S_PAYMENT_COMPLETION)) || (_sw16500000_ == S_NO_SHOW)) || (_sw16500000_ == S_VOICE_AUTHORISATION)) || (_sw16500000_ == S_CARDHOLDER_DETECTION)) {
    } else {
        /* item 1668 */
        result = PR_NOK;
        goto item_1820;
    }
    
    // item 1670
    if ((((g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .cardInserted) || (g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .cardSwiped)) || (g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .manualEntry)) || (g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .accept)) {
        /* item 1676 */
        result = PR_REINITIALISE;
    } else {
        /* item 1681 */
        /* item 1680 */
        g_Nexo.ServiceStartEvents
        [g_Ctd.SelectedService]
        .referenceEntry = 1;
        /* item 1685 */
        result = PR_DONE;
    }
    
    item_1820 :
    return result;
    
}

static enum ProcedureResult Process_Service_Selection(void) {
    // item 1794
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 1599 */
    result =
    Service_Initialisation();
    
    // item 1600
    if (PR_OK == result) {
        /* item 1795 */
        g_Ctd.TerminalErrorIndicator = false;
        /* item 1793 */
        result = PR_OK;
        goto item_1796;
    } else {
        /* item 1603 */
        g_Ctd.TerminalErrorIndicator = true;
        /* item 1605 */
        g_Ctd.NokReason = N_TECHNICAL_ERROR;
    }
    
    // item 1606
    if (g_Ctd.TerminalErrorReason
    ==
    TE_NONE) {
        /* item 1609 */
        g_Ctd.TerminalErrorReason = TE_UNSPECIFIED;
    } else {
    }
    
    // item 1604
    result = PR_NOK;
    
    item_1796 :
    return result;
    
}

static enum ProcedureResult Profile_Selection(void) {
    // item 1744
    return PR_OK;
    
}

static enum ProcedureResult Service_Initialisation(void) {
    // item 1781
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 1845 */
    bool SecurityPermission = false;
    /* item 1562 */
    Initialise_Transaction_Database();
    
    // item 1563
    if (g_Ctd.SelectedService == S_NONE) {
        /* item 1564 */
        DeactivateAllInterfaces();
        /* item 1565 */
        result =
        Output(0x1E);
    } else {
        /* item 1598 */
        goto item_1576;
    }
    
    // item 1566
    if (PR_DONE == result) {
        goto item_1591;
    } else {
        goto item_1570;
    }
    
    item_1576 :
    if (g_Nexo.ServiceSettings
    [g_Ctd.SelectedService]
    .ServiceProtected) {
        /* item 1593 */
        SecurityPermission =
        Authorise_Service();
    } else {
        goto item_1583;
    }
    
    // item 1594
    if (SecurityPermission) {
    } else {
        /* item 1595 */
        g_Ctd.NokReason = N_NO_PERMISSION;
        goto item_1570;
    }
    
    item_1583 :
    result =
    Update_Cardholder_Initial_Message();
    
    // item 1584
    if (PR_OK == result) {
        /* item 1587 */
        result =
        Enable_Allowed_Interfaces();
    } else {
        goto item_1570;
    }
    
    // item 1592
    if (PR_DONE == result) {
    } else {
        goto item_1570;
    }
    
    item_1591 :
    result = PR_OK;
    goto item_1782;
    
    item_1570 :
    result = PR_NOK;
    
    item_1782 :
    return result;
    
}

static enum ProcedureResult Technology_Selection(void) {
    // item 1741
    return PR_OK;
    
}

static enum ProcedureResult Transaction_Completion(void) {
    // item 1768
    return PR_DONE;
    
}

static enum ProcedureResult Transaction_Dcc_Eligibility(void) {
    // item 1852
    enum ProcedureResult result = PR_UNINITIALISED;
    
    // item 878
    if (g_Nexo.ApplicationProfileSettings
    .isDccAcceptorModeAllowed) {
    } else {
        goto item_1858;
    }
    
    // item 881
    if (g_Nexo.ApplicationCurrency) {
    } else {
        goto item_885;
    }
    
    // item 883
    if (g_Nexo.ApplicationCurrency->Code
    ==
    g_Ctd.TransactionCurrency.Code) {
        goto item_1858;
    } else {
        goto item_891;
    }
    
    item_885 :
    if ((g_Ctd.IssuerCountry) && (isIssuerCountryExcludedForDcc())) {
        goto item_1858;
    } else {
    }
    
    item_891 :
    /* item 1846 */
    result = PR_NOT_IMPLEMENTED;
    
    // item 8920001
    if ((result == PR_NO_MATCH) || (result == PR_NOT_IMPLEMENTED)) {
        /* item 890 */
        g_Ctd.isDccEligible = true;
        goto item_1848;
    } else {
    }
    
    item_1858 :
    g_Ctd.isDccEligible = false;
    
    item_1848 :
    result = PR_DONE;
    /* item 1847 */
    return result;
    
}

static enum ProcedureResult Upa_Specific_Processing(void) {
    // item 1828
    enum ProcedureResult result = PR_UNINITIALISED;
    
    // item 1038
    if (g_Nexo.TerminalSettings
    .retrievePreauth) {
    } else {
        goto item_1090;
    }
    
    // item 1041
    if (g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .referenceEntry) {
        /* item 1055 */
        result =
        SearchReservationsByRefData();
        goto item_10570001;
    } else {
    }
    
    // item 1044
    if (g_Ctd.PAN) {
        /* item 1056 */
        result =
        SearchReservationsByPan();
    } else {
        goto item_1085;
    }
    
    item_10570001 :
    if (result == PR_OK) {
        /* item 1048 */
        result =
        SCAP_Search_Transaction_Result_List();
    } else {
        goto item_10570002;
    }
    
    // item 1136
    if (PR_DONE == result) {
        /* item 1143 */
        result =
        Log_Entry_Data_Retrieval();
    } else {
        goto item_1085;
    }
    
    // item 1071
    if (PR_OK == result) {
    } else {
        /* item 1074 */
        g_Ctd.NokReason = N_MISSING_DATA
        /**/;
        goto item_1085;
    }
    
    // item 1079
    if (g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .referenceEntry) {
        /* item 1081 */
        result =
        Process_Profile_Parameters();
    } else {
        goto item_1090;
    }
    
    // item 1082
    if (PR_OK == result) {
        goto item_1090;
    } else {
        goto item_1085;
    }
    
    item_10570002 :
    if (result == PR_NOT_FOUND) {
        /* item 1066 */
        SCAP_NoOriginalTransaction();
        /* item 1065 */
        g_Ctd.NokReason = N_ORIGINAL_TRX_NOT_FOUND;
        goto item_1085;
    } else {
        /* item 1067 */
        g_Ctd.NokReason = N_TECHNICAL_ERROR;
        goto item_1085;
    }
    
    item_1090 :
    if (g_Ctd.TransactionAmountEntered) {
        /* item 1095 */
        result =
        UpdatePreAuthAmountConfirmation();
    } else {
        /* item 1093 */
        g_Ctd.TransactionAmount = (union Amount){ .bcd = { 0 } };
        /* item 1094 */
        result =
        UpdatePreAuthAmountEntry();
        goto item_1096;
    }
    
    // item 1099
    if (PR_DONE == result) {
        goto item_1107;
    } else {
        goto item_1085;
    }
    
    item_1096 :
    if (PR_DONE == result) {
        /* item 1098 */
        g_Ctd.TransactionAmountEntered = true;
    } else {
        goto item_1085;
    }
    
    item_1107 :
    SetUpdatePreAuthTotalAmount();
    
    // item 1108
    if (g_Nexo.ServiceStartEvents
    [g_Ctd.SelectedService]
    .referenceEntry) {
        /* item 1111 */
        result =
        OnlineApprovalRequest();
    } else {
        /* item 1110 */
        result = PR_ONLINE;
        goto item_1832;
    }
    
    // item 11120001
    if (result == PR_DONE) {
        goto item_1087;
    } else {
    }
    
    // item 11120002
    if (result == PR_UNABLE_TO_GO_ONLINE) {
        /* item 1122 */
        g_Ctd.TransactionResult = T_DECLINED;
        /* item 1123 */
        g_Ctd.
        AuthorisationResponseCode = (struct AuthorisationResponseCode)
        { .v = { 'Z', '1' } };
    } else {
        goto item_1085;
    }
    
    item_1087 :
    result = PR_OK;
    goto item_1832;
    
    item_1085 :
    result = PR_NOK;
    
    item_1832 :
    return result;
    
}

static enum ProcedureResult Update_Pre_Authorisation(void) {
    int _sw9670000_ = 0;
    // item 1863
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 923 */
    result =
    Pre_Processing();
    
    // item 10050001
    if (result == PR_OK) {
        goto item_927;
    } else {
    }
    
    // item 10050002
    if (result == PR_REFERENCE_ENTRY) {
        /* item 1022 */
        result =
        Upa_Specific_Processing();
    } else {
        goto item_990;
    }
    
    // item 10130001
    if (result == PR_DONE) {
    } else {
        goto item_10130002;
    }
    
    item_964 :
    result =
    Online_Request();
    
    // item 998
    if (PR_OK == result) {
        /* item 9670000 */
        _sw9670000_ = g_Ctd.Out.Start;
    } else {
        goto item_990;
    }
    
    // item 9670001
    if (_sw9670000_ == NONE) {
        /* item 974 */
        result =
        Check_Online_Performed();
    } else {
        goto item_9670002;
    }
    
    // item 975
    if (PR_OK == result) {
        goto item_991;
    } else {
        goto item_990;
    }
    
    item_9670002 :
    if (_sw9670000_ == B) {
        goto item_927;
    } else {
    }
    
    // item 9670003
    if (_sw9670000_ == C) {
    } else {
        goto item_9670004;
    }
    
    item_928 :
    result =
    Profile_Selection();
    
    // item 9290001
    if (result == PR_OK) {
        /* item 948 */
        result =
        Cvc_Check_Amount();
    } else {
        goto item_9290002;
    }
    
    // item 949
    if (PR_OK == result) {
        goto item_953;
    } else {
        goto item_990;
    }
    
    item_9290002 :
    if (result == PR_TAP_AGAIN) {
    } else {
        goto item_9290003;
    }
    
    item_927 :
    result =
    Technology_Selection();
    
    // item 9400001
    if (result == PR_NON_EMV) {
        /* item 993 */
        goto item_990;
    } else {
    }
    
    // item 9400002
    if (result == PR_NOK) {
        goto item_990;
    } else {
        goto item_928;
    }
    
    item_9290003 :
    if (result == PR_END_APPLICATION) {
        goto item_961;
    } else {
        goto item_991;
    }
    
    item_9670004 :
    if (_sw9670000_ == D) {
    } else {
        goto item_990;
    }
    
    item_953 :
    result =
    Kernel_Activation();
    
    // item 954
    if (PR_OK == result) {
        /* item 958 */
        result =
        Kernel_Processing();
    } else {
        goto item_990;
    }
    
    // item 959
    if (PR_OK == result) {
    } else {
        goto item_990;
    }
    
    item_961 :
    result =
    Outcome_Processing();
    
    // item 965
    if (PR_OK == result) {
    } else {
        goto item_990;
    }
    
    // item 962
    if (g_Ctd.Outcome == O_ONLINE_REQUEST) {
        goto item_991;
    } else {
        goto item_964;
    }
    
    item_10130002 :
    if (result == PR_OK) {
        goto item_991;
    } else {
    }
    
    item_990 :
    g_Ctd.TransactionResult = T_ABORTED;
    
    item_991 :
    Transaction_Completion();
    /* item 1833 */
    return PR_DONE;
    
}

enum ProcedureResult Main(void) {
    int _sw11840000_ = 0;
    int _sw18760000_ = 0;
    int _sw18670000_ = 0;
    // item 1728
    enum ProcedureResult result = PR_UNINITIALISED;
    /* item 1724 */
    result =
    Proprietary_Startup_Sequence();
    
    // item 1160
    if (PR_OK == result) {
    } else {
        goto item_1875;
    }
    
    item_1505 :
    result =
    Financial_Application_Startup();
    
    // item 1169
    if (PR_OK == result) {
    } else {
        goto item_1875;
    }
    
    item_1175 :
    result =
    Default_Service_Initialisation();
    
    // item 1176
    if (PR_OK == result) {
    } else {
        goto item_1875;
    }
    
    item_1182 :
    result =
    Wait_For_Event(
    	&g_Ctd.Event,
    	&g_Ctd.ReferenceData,
    	&g_Ctd.SelectedService
    );
    
    // item 18840001
    if (result == PR_NEW_EVENT) {
        /* item 11840000 */
        _sw11840000_ = Process_Event();;
    } else {
        goto item_1875;
    }
    
    // item 11840001
    if (_sw11840000_ == PR_OK) {
        /* item 18760000 */
        _sw18760000_ = Check_Service_Start_Conditions();;
    } else {
        goto item_11840002;
    }
    
    // item 18760001
    if (_sw18760000_ == PR_CONDITIONS_SATISFIED) {
        /* item 18670000 */
        _sw18670000_ = Perform_Service();
    } else {
        goto item_18760002;
    }
    
    // item 18670001
    if (_sw18670000_ == PR_OK) {
        goto item_1175;
    } else {
    }
    
    // item 18670002
    if (_sw18670000_ == PR_NOK) {
        goto item_1505;
    } else {
        goto item_1875;
    }
    
    item_18760002 :
    if (_sw18760000_ == PR_CONDITIONS_NOT_SATISFIED) {
        goto item_1182;
    } else {
        goto item_1875;
    }
    
    item_11840002 :
    if (_sw11840000_ == PR_REINITIALISE) {
        goto item_1175;
    } else {
    }
    
    // item 11840003
    if (_sw11840000_ == PR_NOK) {
        goto item_1505;
    } else {
    }
    
    item_1875 :
    result =
    Diagnostics_Maintenance_Recovery();
    /* item 1726 */
    return result;
    
}



